import type { Room, Building, TimeSlot } from "./types"

export const buildings: Building[] = [
  { id: "new", name: "New Building", floors: [1, 2, 3] },
  { id: "old", name: "Old Building", floors: [1, 2] },
  { id: "science", name: "Science Building", floors: [1, 2, 3, 4] },
  { id: "engineering", name: "Engineering Building", floors: [1, 2, 3] },
]

export const mockRooms: Room[] = [
  // New Building - Floor 1 - A Block - Lecture Halls
  {
    id: "LHA001",
    name: "LHA 001",
    capacity: 120,
    type: "lecture-hall",
    status: "available",
    equipment: ["Projector", "Audio System"],
    block: "A",
    building: "new",
    floor: 1,
  },
  {
    id: "LHA002",
    name: "LHA 002",
    capacity: 80,
    type: "lecture-hall",
    status: "available",
    equipment: ["Projector", "Whiteboard"],
    block: "A",
    building: "new",
    floor: 1,
  },
  {
    id: "LHA003",
    name: "LHA 003",
    capacity: 150,
    type: "lecture-hall",
    status: "available",
    equipment: ["Projector", "Audio System", "Recording"],
    block: "A",
    building: "new",
    floor: 1,
  },
  {
    id: "LHA004",
    name: "LHA 004",
    capacity: 100,
    type: "lecture-hall",
    status: "available",
    equipment: ["Projector", "Whiteboard"],
    block: "A",
    building: "new",
    floor: 1,
  },
  // New Building - Floor 1 - B Block - Lecture Halls
  {
    id: "LHB001",
    name: "LHB 001",
    capacity: 90,
    type: "lecture-hall",
    status: "available",
    equipment: ["Projector", "Audio System"],
    block: "B",
    building: "new",
    floor: 1,
  },
  {
    id: "LHB002",
    name: "LHB 002",
    capacity: 110,
    type: "lecture-hall",
    status: "available",
    equipment: ["Projector", "Whiteboard"],
    block: "B",
    building: "new",
    floor: 1,
  },
  // Labs
  {
    id: "LBA001",
    name: "LBA 001",
    capacity: 30,
    type: "lab",
    status: "available",
    equipment: ["Computers", "Projector"],
    block: "A",
    building: "new",
    floor: 1,
  },
  {
    id: "LBA002",
    name: "LBA 002",
    capacity: 25,
    type: "lab",
    status: "reserved",
    equipment: ["Computers", "Lab Equipment"],
    block: "A",
    building: "new",
    floor: 1,
  },
  // Science Building
  {
    id: "SLA001",
    name: "SLA 001",
    capacity: 40,
    type: "lab",
    status: "available",
    equipment: ["Microscopes", "Lab Equipment"],
    block: "A",
    building: "science",
    floor: 1,
  },
  {
    id: "SLA002",
    name: "SLA 002",
    capacity: 35,
    type: "lab",
    status: "reserved",
    equipment: ["Chemicals", "Fume Hoods"],
    block: "A",
    building: "science",
    floor: 1,
  },
]

// Mock timetable data - represents booked time slots
export const mockTimeSlots: TimeSlot[] = [
  {
    id: "ts001",
    roomId: "LHA001",
    date: "2025-09-03",
    startTime: "09:00",
    endTime: "10:30",
    isBooked: true,
    bookedBy: "Dr. Smith",
    purpose: "Computer Science Lecture",
  },
  {
    id: "ts002",
    roomId: "LHA001",
    date: "2025-09-03",
    startTime: "14:00",
    endTime: "15:30",
    isBooked: true,
    bookedBy: "Prof. Johnson",
    purpose: "Mathematics Lecture",
  },
  {
    id: "ts003",
    roomId: "LBA001",
    date: "2025-09-03",
    startTime: "10:00",
    endTime: "12:00",
    isBooked: true,
    bookedBy: "Dr. Wilson",
    purpose: "Programming Lab",
  },
  {
    id: "ts004",
    roomId: "SLA001",
    date: "2025-09-03",
    startTime: "13:00",
    endTime: "16:00",
    isBooked: true,
    bookedBy: "Dr. Brown",
    purpose: "Biology Practical",
  },
  {
    id: "ts005",
    roomId: "LHA002",
    date: "2025-09-04",
    startTime: "11:00",
    endTime: "12:30",
    isBooked: true,
    bookedBy: "Prof. Davis",
    purpose: "Physics Lecture",
  },
]
